# Generated by Django 4.2.27 on 2025-12-11 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Motorista",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome Completo"),
                ),
                (
                    "cpf",
                    models.CharField(db_index=True, max_length=14, verbose_name="CPF"),
                ),
                ("rg", models.CharField(blank=True, max_length=20, verbose_name="RG")),
                (
                    "data_nascimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Nascimento"
                    ),
                ),
                (
                    "cnh_numero",
                    models.CharField(max_length=20, verbose_name="Número CNH"),
                ),
                (
                    "cnh_categoria",
                    models.CharField(
                        choices=[
                            ("A", "A - Motocicleta"),
                            ("B", "B - Carro"),
                            ("C", "C - Caminhão"),
                            ("D", "D - Ônibus"),
                            ("E", "E - Carreta"),
                            ("AB", "AB"),
                            ("AC", "AC"),
                            ("AD", "AD"),
                            ("AE", "AE"),
                        ],
                        max_length=3,
                        verbose_name="Categoria CNH",
                    ),
                ),
                ("cnh_validade", models.DateField(verbose_name="Validade CNH")),
                (
                    "cnh_primeira_habilitacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Primeira Habilitação"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                ("celular", models.CharField(max_length=20, verbose_name="Celular")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "cep",
                    models.CharField(blank=True, max_length=10, verbose_name="CEP"),
                ),
                (
                    "endereco",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Endereço"
                    ),
                ),
                (
                    "cidade",
                    models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
                ),
                ("uf", models.CharField(blank=True, max_length=2, verbose_name="UF")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("inativo", "Inativo"),
                            ("ferias", "Férias"),
                            ("afastado", "Afastado"),
                            ("desligado", "Desligado"),
                        ],
                        default="ativo",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_admissao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Admissão"
                    ),
                ),
                (
                    "data_demissao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Demissão"
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="motoristas/fotos/",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "cnh_arquivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="motoristas/cnh/",
                        verbose_name="Arquivo CNH",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="motorista_perfil",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário do Sistema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Motorista",
                "verbose_name_plural": "Motoristas",
                "ordering": ["nome"],
                "unique_together": {("tenant", "cpf")},
            },
        ),
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "placa",
                    models.CharField(
                        db_index=True, max_length=10, verbose_name="Placa"
                    ),
                ),
                (
                    "renavam",
                    models.CharField(blank=True, max_length=20, verbose_name="RENAVAM"),
                ),
                (
                    "chassi",
                    models.CharField(blank=True, max_length=20, verbose_name="Chassi"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("moto", "Motocicleta"),
                            ("fiorino", "Fiorino/Kangoo"),
                            ("van", "Van"),
                            ("vuc", "VUC"),
                            ("toco", "Caminhão Toco"),
                            ("truck", "Caminhão Truck"),
                            ("carreta", "Carreta"),
                            ("bitrem", "Bitrem"),
                            ("rodotrem", "Rodotrem"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "marca",
                    models.CharField(blank=True, max_length=50, verbose_name="Marca"),
                ),
                (
                    "modelo",
                    models.CharField(blank=True, max_length=100, verbose_name="Modelo"),
                ),
                (
                    "ano_fabricacao",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ano Fabricação"
                    ),
                ),
                (
                    "ano_modelo",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ano Modelo"
                    ),
                ),
                (
                    "cor",
                    models.CharField(blank=True, max_length=30, verbose_name="Cor"),
                ),
                (
                    "capacidade_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Capacidade (kg)",
                    ),
                ),
                (
                    "capacidade_m3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Capacidade (m³)",
                    ),
                ),
                (
                    "documento_vencimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vencimento do Documento"
                    ),
                ),
                (
                    "seguro_vencimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vencimento do Seguro"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("disponivel", "Disponível"),
                            ("em_viagem", "Em Viagem"),
                            ("manutencao", "Em Manutenção"),
                            ("reservado", "Reservado"),
                            ("inativo", "Inativo"),
                        ],
                        default="disponivel",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "km_atual",
                    models.PositiveIntegerField(default=0, verbose_name="KM Atual"),
                ),
                (
                    "ultima_manutencao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Última Manutenção"
                    ),
                ),
                (
                    "proxima_manutencao_km",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Próxima Manutenção (KM)"
                    ),
                ),
                (
                    "propriedade",
                    models.CharField(
                        choices=[
                            ("proprio", "Próprio"),
                            ("terceiro", "Terceiro"),
                            ("agregado", "Agregado"),
                            ("alugado", "Alugado"),
                        ],
                        default="proprio",
                        max_length=20,
                        verbose_name="Propriedade",
                    ),
                ),
                (
                    "proprietario_nome",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nome do Proprietário"
                    ),
                ),
                (
                    "proprietario_cpf_cnpj",
                    models.CharField(
                        blank=True, max_length=18, verbose_name="CPF/CNPJ Proprietário"
                    ),
                ),
                (
                    "rastreador_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ID do Rastreador"
                    ),
                ),
                (
                    "rastreador_modelo",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Modelo Rastreador"
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="veiculos/",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "motorista_fixo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="veiculos",
                        to="frota.motorista",
                        verbose_name="Motorista Fixo",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veículo",
                "verbose_name_plural": "Veículos",
                "ordering": ["placa"],
                "unique_together": {("tenant", "placa")},
            },
        ),
        migrations.CreateModel(
            name="Manutencao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("preventiva", "Preventiva"),
                            ("corretiva", "Corretiva"),
                            ("revisao", "Revisão"),
                            ("troca_pneu", "Troca de Pneu"),
                            ("troca_oleo", "Troca de Óleo"),
                            ("documentacao", "Documentação"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "km_realizacao",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="KM na Realização"
                    ),
                ),
                ("data_entrada", models.DateField(verbose_name="Data de Entrada")),
                (
                    "data_saida",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Saída"
                    ),
                ),
                (
                    "previsao_saida",
                    models.DateField(
                        blank=True, null=True, verbose_name="Previsão de Saída"
                    ),
                ),
                (
                    "fornecedor",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Fornecedor/Oficina"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("agendada", "Agendada"),
                            ("em_andamento", "Em Andamento"),
                            ("concluida", "Concluída"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="agendada",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manutencoes",
                        to="frota.veiculo",
                        verbose_name="Veículo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manutenção",
                "verbose_name_plural": "Manutenções",
                "ordering": ["-data_entrada"],
            },
        ),
    ]
