# Generated by Django 4.2.27 on 2025-12-11 23:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "razao_social",
                    models.CharField(max_length=255, verbose_name="Razão Social"),
                ),
                (
                    "nome_fantasia",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nome Fantasia"
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(db_index=True, max_length=18, verbose_name="CNPJ"),
                ),
                (
                    "inscricao_estadual",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Inscrição Estadual"
                    ),
                ),
                (
                    "contato_nome",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Nome do Contato"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "celular",
                    models.CharField(blank=True, max_length=20, verbose_name="Celular"),
                ),
                (
                    "cep",
                    models.CharField(blank=True, max_length=10, verbose_name="CEP"),
                ),
                (
                    "logradouro",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Logradouro"
                    ),
                ),
                (
                    "numero",
                    models.CharField(blank=True, max_length=20, verbose_name="Número"),
                ),
                (
                    "complemento",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Complemento"
                    ),
                ),
                (
                    "bairro",
                    models.CharField(blank=True, max_length=100, verbose_name="Bairro"),
                ),
                (
                    "cidade",
                    models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
                ),
                ("uf", models.CharField(blank=True, max_length=2, verbose_name="UF")),
                (
                    "condicao_pagamento",
                    models.CharField(
                        choices=[
                            ("a_vista", "À Vista"),
                            ("7_dias", "7 dias"),
                            ("14_dias", "14 dias"),
                            ("21_dias", "21 dias"),
                            ("28_dias", "28 dias"),
                            ("30_dias", "30 dias"),
                            ("45_dias", "45 dias"),
                            ("60_dias", "60 dias"),
                            ("faturado", "Faturado"),
                        ],
                        default="30_dias",
                        max_length=20,
                        verbose_name="Condição de Pagamento",
                    ),
                ),
                (
                    "limite_credito",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Limite de Crédito",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["razao_social"],
            },
        ),
        migrations.CreateModel(
            name="ContatoCliente",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("nome", models.CharField(max_length=150, verbose_name="Nome")),
                (
                    "cargo",
                    models.CharField(blank=True, max_length=100, verbose_name="Cargo"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "celular",
                    models.CharField(blank=True, max_length=20, verbose_name="Celular"),
                ),
                (
                    "is_principal",
                    models.BooleanField(
                        default=False, verbose_name="Contato Principal"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contatos",
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contato",
                "verbose_name_plural": "Contatos",
            },
        ),
    ]
