# Generated by Django 4.2.27 on 2025-12-11 23:40

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clientes", "0001_initial"),
        ("comercial", "0001_initial"),
        ("core", "0001_initial"),
        ("frota", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PedidoFrete",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "numero",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Número do Pedido"
                    ),
                ),
                (
                    "data_pedido",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Data do Pedido"
                    ),
                ),
                (
                    "origem_cep",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="CEP Origem"
                    ),
                ),
                (
                    "origem_endereco",
                    models.CharField(max_length=255, verbose_name="Endereço Origem"),
                ),
                (
                    "origem_cidade",
                    models.CharField(max_length=100, verbose_name="Cidade Origem"),
                ),
                ("origem_uf", models.CharField(max_length=2, verbose_name="UF Origem")),
                (
                    "remetente_nome",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nome do Remetente"
                    ),
                ),
                (
                    "remetente_telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone Remetente"
                    ),
                ),
                (
                    "destino_cep",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="CEP Destino"
                    ),
                ),
                (
                    "destino_endereco",
                    models.CharField(max_length=255, verbose_name="Endereço Destino"),
                ),
                (
                    "destino_cidade",
                    models.CharField(max_length=100, verbose_name="Cidade Destino"),
                ),
                (
                    "destino_uf",
                    models.CharField(max_length=2, verbose_name="UF Destino"),
                ),
                (
                    "destinatario_nome",
                    models.CharField(
                        max_length=200, verbose_name="Nome do Destinatário"
                    ),
                ),
                (
                    "destinatario_telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone Destinatário"
                    ),
                ),
                (
                    "destinatario_documento",
                    models.CharField(
                        blank=True, max_length=18, verbose_name="CPF/CNPJ Destinatário"
                    ),
                ),
                (
                    "tipo_carga",
                    models.CharField(max_length=30, verbose_name="Tipo de Carga"),
                ),
                (
                    "peso_kg",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Peso (kg)"
                    ),
                ),
                (
                    "cubagem_m3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Cubagem (m³)",
                    ),
                ),
                (
                    "quantidade_volumes",
                    models.PositiveIntegerField(default=1, verbose_name="Qtd. Volumes"),
                ),
                (
                    "valor_mercadoria",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor da Mercadoria",
                    ),
                ),
                (
                    "descricao_carga",
                    models.TextField(blank=True, verbose_name="Descrição da Carga"),
                ),
                (
                    "valor_frete",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor do Frete"
                    ),
                ),
                (
                    "valor_seguro",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Valor do Seguro",
                    ),
                ),
                (
                    "valor_adicional",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Valor Adicional",
                    ),
                ),
                (
                    "custo_estimado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Custo Estimado",
                    ),
                ),
                (
                    "previsao_coleta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Previsão de Coleta"
                    ),
                ),
                (
                    "data_coleta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Coleta"
                    ),
                ),
                (
                    "previsao_entrega",
                    models.DateField(verbose_name="Previsão de Entrega"),
                ),
                (
                    "data_entrega",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data da Entrega"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("em_planejamento", "Em Planejamento"),
                            ("aguardando_coleta", "Aguardando Coleta"),
                            ("em_coleta", "Em Coleta"),
                            ("coletado", "Coletado"),
                            ("em_transito", "Em Trânsito"),
                            ("em_transferencia", "Em Transferência"),
                            ("saiu_entrega", "Saiu para Entrega"),
                            ("entregue", "Entregue"),
                            ("tentativa_entrega", "Tentativa de Entrega"),
                            ("devolvido", "Devolvido"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="em_planejamento",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "sla_status",
                    models.CharField(
                        choices=[
                            ("verde", "No Prazo"),
                            ("amarelo", "Atenção"),
                            ("vermelho", "Atrasado"),
                        ],
                        default="verde",
                        max_length=10,
                        verbose_name="SLA",
                    ),
                ),
                (
                    "cte_numero",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Número CT-e"
                    ),
                ),
                (
                    "cte_chave",
                    models.CharField(
                        blank=True, max_length=44, verbose_name="Chave CT-e"
                    ),
                ),
                (
                    "cte_status",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Status CT-e"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos",
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "cotacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos",
                        to="comercial.cotacao",
                        verbose_name="Cotação",
                    ),
                ),
                (
                    "motorista",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos",
                        to="frota.motorista",
                        verbose_name="Motorista",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos",
                        to="frota.veiculo",
                        verbose_name="Veículo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido de Frete",
                "verbose_name_plural": "Pedidos de Frete",
                "ordering": ["-data_pedido", "-created_at"],
                "unique_together": {("tenant", "numero")},
            },
        ),
        migrations.CreateModel(
            name="EventoRastreamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "tipo",
                    models.CharField(max_length=50, verbose_name="Tipo do Evento"),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                (
                    "local",
                    models.CharField(blank=True, max_length=255, verbose_name="Local"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "data_evento",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Data do Evento"
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="operacional.pedidofrete",
                        verbose_name="Pedido",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de Rastreamento",
                "verbose_name_plural": "Eventos de Rastreamento",
                "ordering": ["-data_evento"],
            },
        ),
        migrations.CreateModel(
            name="Entrega",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aguardando", "Aguardando"),
                            ("em_rota", "Em Rota"),
                            ("chegou_destino", "Chegou ao Destino"),
                            ("entregue", "Entregue"),
                            ("entregue_parcial", "Entregue Parcialmente"),
                            ("ausente", "Destinatário Ausente"),
                            ("recusado", "Recusado"),
                            ("endereco_incorreto", "Endereço Incorreto"),
                            ("avariado", "Avariado"),
                            ("devolvido", "Devolvido"),
                        ],
                        default="aguardando",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "local_descricao",
                    models.CharField(blank=True, max_length=255, verbose_name="Local"),
                ),
                (
                    "recebedor_nome",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nome do Recebedor"
                    ),
                ),
                (
                    "recebedor_documento",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Documento do Recebedor"
                    ),
                ),
                (
                    "foto_comprovante",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="comprovantes/",
                        verbose_name="Foto Comprovante",
                    ),
                ),
                (
                    "assinatura",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="assinaturas/",
                        verbose_name="Assinatura",
                    ),
                ),
                (
                    "data_evento",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Data do Evento"
                    ),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="Observação")),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entregas",
                        to="operacional.pedidofrete",
                        verbose_name="Pedido",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrega",
                "verbose_name_plural": "Entregas",
                "ordering": ["-data_evento"],
            },
        ),
    ]
