# Generated by Django 4.2.27 on 2025-12-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operacional", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedidofrete",
            name="numero",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=20,
                verbose_name="Número do Pedido",
            ),
        ),
    ]
