# Generated by Django 4.2.27 on 2025-12-11 23:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("operacional", "0001_initial"),
        ("core", "0001_initial"),
        ("frota", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CTe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("numero", models.CharField(blank=True, max_length=20)),
                ("serie", models.CharField(default="1", max_length=5)),
                ("chave", models.CharField(blank=True, max_length=44)),
                ("protocolo", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("processando", "Processando"),
                            ("autorizado", "Autorizado"),
                            ("cancelado", "Cancelado"),
                            ("rejeitado", "Rejeitado"),
                        ],
                        default="rascunho",
                        max_length=20,
                    ),
                ),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("valor_servico", models.DecimalField(decimal_places=2, max_digits=12)),
                ("valor_carga", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "icms_base",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "icms_aliquota",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "icms_valor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("focusnfe_id", models.CharField(blank=True, max_length=100)),
                ("focusnfe_ref", models.CharField(blank=True, max_length=100)),
                ("xml_autorizacao", models.TextField(blank=True)),
                ("pdf_url", models.URLField(blank=True)),
                ("data_emissao", models.DateTimeField(blank=True, null=True)),
                ("data_autorizacao", models.DateTimeField(blank=True, null=True)),
                ("mensagem_erro", models.TextField(blank=True)),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ctes",
                        to="operacional.pedidofrete",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "CT-e",
                "verbose_name_plural": "CT-es",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MDFe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("numero", models.CharField(blank=True, max_length=20)),
                ("serie", models.CharField(default="1", max_length=5)),
                ("chave", models.CharField(blank=True, max_length=44)),
                ("protocolo", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("processando", "Processando"),
                            ("autorizado", "Autorizado"),
                            ("encerrado", "Encerrado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="rascunho",
                        max_length=20,
                    ),
                ),
                ("uf_inicio", models.CharField(max_length=2)),
                ("uf_fim", models.CharField(max_length=2)),
                ("focusnfe_id", models.CharField(blank=True, max_length=100)),
                ("focusnfe_ref", models.CharField(blank=True, max_length=100)),
                ("xml_autorizacao", models.TextField(blank=True)),
                ("pdf_url", models.URLField(blank=True)),
                ("data_emissao", models.DateTimeField(blank=True, null=True)),
                ("data_autorizacao", models.DateTimeField(blank=True, null=True)),
                ("data_encerramento", models.DateTimeField(blank=True, null=True)),
                ("mensagem_erro", models.TextField(blank=True)),
                ("ctes", models.ManyToManyField(related_name="mdfes", to="fiscal.cte")),
                (
                    "motorista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="frota.motorista",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="frota.veiculo"
                    ),
                ),
            ],
            options={
                "verbose_name": "MDF-e",
                "verbose_name_plural": "MDF-es",
                "ordering": ["-created_at"],
            },
        ),
    ]
