"""Add vehicle and order limits to tenants

Revision ID: a17df79457cb
Revises: 4bf7fd72fe00
Create Date: 2025-12-13 20:23:32.959594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a17df79457cb'
down_revision: Union[str, Sequence[str], None] = '4bf7fd72fe00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('max_vehicles', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('max_orders_per_month', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'max_orders_per_month')
    op.drop_column('tenants', 'max_vehicles')
    # ### end Alembic commands ###
