services:
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v1.8.0
    restart: always
    ports:
      - "8080:8080"
    environment:
      - AUTHENTICATION_API_KEY=logiflow-evolution-key-2025
    volumes:
      - evolution_store:/evolution/store
      - evolution_instances:/evolution/instances

volumes:
  evolution_store:
  evolution_instances:
