# Generated by Django 4.2.27 on 2025-12-12 00:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0002_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SLAConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "limite_verde",
                    models.PositiveIntegerField(
                        default=2,
                        help_text='Pedidos com mais dias que este valor são considerados "No Prazo"',
                        verbose_name="Limite Verde (dias)",
                    ),
                ),
                (
                    "limite_amarelo",
                    models.PositiveIntegerField(
                        default=1,
                        help_text='Pedidos com dias entre amarelo e verde são considerados "Atenção"',
                        verbose_name="Limite Amarelo (dias)",
                    ),
                ),
                (
                    "considerar_dias_uteis",
                    models.BooleanField(
                        default=False, verbose_name="Considerar apenas dias úteis"
                    ),
                ),
                (
                    "alertar_sla_amarelo",
                    models.BooleanField(
                        default=True,
                        verbose_name="Enviar alerta quando SLA ficar amarelo",
                    ),
                ),
                (
                    "alertar_sla_vermelho",
                    models.BooleanField(
                        default=True,
                        verbose_name="Enviar alerta quando SLA ficar vermelho",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de SLA",
                "verbose_name_plural": "Configurações de SLA",
            },
        ),
        migrations.CreateModel(
            name="SLAClienteConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "limite_verde",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Limite Verde (dias)",
                    ),
                ),
                (
                    "limite_amarelo",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Limite Amarelo (dias)",
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("alta", "Alta"),
                            ("vip", "VIP"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "bonus_horas",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Horas a serem subtraídas do prazo para clientes VIP",
                        verbose_name="Bônus de horas (reduz SLA)",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "cliente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_config",
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "SLA por Cliente",
                "verbose_name_plural": "SLAs por Cliente",
            },
        ),
        migrations.CreateModel(
            name="SLARotaConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("nome", models.CharField(max_length=100, verbose_name="Nome da Rota")),
                ("origem_uf", models.CharField(max_length=2, verbose_name="UF Origem")),
                (
                    "origem_cidade",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Cidade Origem"
                    ),
                ),
                (
                    "destino_uf",
                    models.CharField(max_length=2, verbose_name="UF Destino"),
                ),
                (
                    "destino_cidade",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Cidade Destino"
                    ),
                ),
                (
                    "dias_adicionais",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Dias extras a serem adicionados ao prazo padrão",
                        verbose_name="Dias adicionais",
                    ),
                ),
                (
                    "limite_verde_customizado",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Limite Verde customizado (dias)",
                    ),
                ),
                (
                    "limite_amarelo_customizado",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Limite Amarelo customizado (dias)",
                    ),
                ),
                (
                    "prazo_medio_dias",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Tempo médio de entrega para esta rota",
                        verbose_name="Prazo médio de entrega (dias)",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="core.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "SLA por Rota",
                "verbose_name_plural": "SLAs por Rota",
                "unique_together": {
                    (
                        "tenant",
                        "origem_uf",
                        "origem_cidade",
                        "destino_uf",
                        "destino_cidade",
                    )
                },
            },
        ),
    ]
