# Generated by Django 4.2.27 on 2025-12-11 23:40

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cotacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "numero",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Número"
                    ),
                ),
                (
                    "contato_nome",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Nome do Contato"
                    ),
                ),
                (
                    "contato_telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone do Contato"
                    ),
                ),
                (
                    "contato_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail do Contato"
                    ),
                ),
                (
                    "origem_cep",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="CEP Origem"
                    ),
                ),
                (
                    "origem_endereco",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Endereço Origem"
                    ),
                ),
                (
                    "origem_cidade",
                    models.CharField(max_length=100, verbose_name="Cidade Origem"),
                ),
                ("origem_uf", models.CharField(max_length=2, verbose_name="UF Origem")),
                (
                    "destino_cep",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="CEP Destino"
                    ),
                ),
                (
                    "destino_endereco",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Endereço Destino"
                    ),
                ),
                (
                    "destino_cidade",
                    models.CharField(max_length=100, verbose_name="Cidade Destino"),
                ),
                (
                    "destino_uf",
                    models.CharField(max_length=2, verbose_name="UF Destino"),
                ),
                (
                    "tipo_carga",
                    models.CharField(
                        choices=[
                            ("geral", "Carga Geral"),
                            ("fracionada", "Fracionada"),
                            ("lotacao", "Lotação Completa"),
                            ("container", "Container"),
                            ("granel_solido", "Granel Sólido"),
                            ("granel_liquido", "Granel Líquido"),
                            ("refrigerada", "Refrigerada"),
                            ("perigosa", "Carga Perigosa"),
                            ("viva", "Carga Viva"),
                            ("indivisivel", "Carga Indivisível"),
                            ("mudanca", "Mudança"),
                        ],
                        default="geral",
                        max_length=30,
                        verbose_name="Tipo de Carga",
                    ),
                ),
                (
                    "peso_kg",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Peso (kg)"
                    ),
                ),
                (
                    "cubagem_m3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Cubagem (m³)",
                    ),
                ),
                (
                    "quantidade_volumes",
                    models.PositiveIntegerField(default=1, verbose_name="Qtd. Volumes"),
                ),
                (
                    "valor_mercadoria",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor da Mercadoria",
                    ),
                ),
                (
                    "descricao_carga",
                    models.TextField(blank=True, verbose_name="Descrição da Carga"),
                ),
                (
                    "modal",
                    models.CharField(
                        choices=[
                            ("rodoviario", "Rodoviário"),
                            ("aereo", "Aéreo"),
                            ("maritimo", "Marítimo"),
                            ("ferroviario", "Ferroviário"),
                            ("fluvial", "Fluvial"),
                            ("multimodal", "Multimodal"),
                        ],
                        default="rodoviario",
                        max_length=20,
                        verbose_name="Modal",
                    ),
                ),
                (
                    "prazo_estimado",
                    models.PositiveIntegerField(verbose_name="Prazo Estimado (dias)"),
                ),
                (
                    "valor_frete",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor do Frete"
                    ),
                ),
                (
                    "valor_seguro",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Valor do Seguro",
                    ),
                ),
                (
                    "valor_adicional",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Valor Adicional",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberta", "Aberta"),
                            ("em_negociacao", "Em Negociação"),
                            ("aprovada", "Aprovada"),
                            ("perdida", "Perdida"),
                            ("expirada", "Expirada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="aberta",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("validade", models.DateField(verbose_name="Válido Até")),
                (
                    "motivo_perda",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("preco", "Preço"),
                            ("prazo", "Prazo"),
                            ("concorrente", "Perdeu para Concorrente"),
                            ("desistencia", "Cliente Desistiu"),
                            ("sem_retorno", "Sem Retorno do Cliente"),
                            ("fora_area", "Fora da Área de Atuação"),
                            ("outro", "Outro"),
                        ],
                        max_length=30,
                        verbose_name="Motivo da Perda",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cotacoes",
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotação",
                "verbose_name_plural": "Cotações",
                "ordering": ["-created_at"],
            },
        ),
    ]
